/**
 * 
 */
package com.seda.payer.core.dao;

import java.util.ResourceBundle;

public enum Routines { 
	USR_DODETAIL,
	USR_DODETAIL_USER,
	USR_DOINSERT,
	USR_DOUPDATE,
	USR_DODELETE,
	USR_SEL_ADMIN,
	USR_GET_PYUSER_AND_APP,
	USR_DOLIST_PRF,
	PRF_DOLIST,
	PRF_DODETAIL,
	PRF_DOINSERT,
	PRF_DOUPDATE,
	PRF_DODELETE,
	SER_DOLIST,
	SER_DODETAIL,
	SER_DOINSERT,
	SER_DOUPDATE,
	SER_DODELETE,
	USER_DOLIST,
	USER_DODETAIL,
	USER_DOINSERT,
	USER_DOUPDATE,
	USER_DODELETE,
	COMPANY_DOLIST,
	COMPANY_DODETAIL,
	COMPANY_DOINSERT,
	COMPANY_DOUPDATE,
	COMPANY_DODELETE,
	AEA_DODETAIL,
	APC_DOLIST,
	APC_DODETAIL,
	APC_DOINSERT,
	APC_DOUPDATE,
	APC_DODELETE,
	APC_DOLIST2,
	APC_DOLIST3,
	APC_DOLIST_EC,
	APC_DOLIST_PG,
	APC_DOLIST_SIGLA,
	APC_DOLIST_SIGLA_TN,
	APC_DOLIST_SIGLA2,
	APC_DOLIST_BELFIORE,
	ANE_DOLIST,
	ANE_DOLIST_INS,
	ANE_DODETAIL,
	ANE_DOINSERT,
	ANE_DOUPDATE,
	ANE_DODELETE,
	ANE_DOLIST2,
	ANE_DOLIST3,
	ANE_DOLIST_EC,
	ANE_DOLIST_PG,
	ANE_DOLIST_TOT,
	ANE_DODETAIL_LIKE,
	ANE_DODETAIL_BELF,
	ANE_DODETAIL_COMUNE,
	ANE_DODETAIL_ENTE,
	ANE_DODETAIL_ENTE2,
	CAN_DOLIST,
	CAN_DODETAIL,
	CAN_DOINSERT,
	CAN_DOUPDATE,
	CAN_DODELETE,
	TSE_DOLIST,
	TSE_DODETAIL,
	TSE_DOINSERT,
	TSE_DOUPDATE,
	TSE_DODELETE,
	TSE_DOLIST_SOC,
	TIO_DOLIST,
	TIO_DODELETE,
	TIO_DODETAIL,
	TIO_DOINS,
	TIO_DOUPD,
	TIO_DODDL,
	ISE_DOLIST,
	ISE_DODETAIL,
	ISE_DOINSERT,
	ISE_DOUPDATE,
	ISE_DODELETE,
	ISE_DOLIST_SOC,
	ENT_DOLIST,
	ENT_DODETAIL,
	ENT_DOINSERT,
	ENT_DOUPDATE,
	ENT_DODELETE,
	ENT_DOLIST_INS,
	ENT_DOLIST_BELF,
	ENC_DOLIST,
	ENC_DODETAIL,
	ENC_DOINSERT,
	ENC_DOUPDATE,
	ENC_DODELETE,
	CFS_DOLIST,
	CFS_DOLIST_INS_BASE,
	CFS_DODETAIL,
	CFS_DOINSERT,
	CFS_DOUPDATE,
	CFS_DODELETE,
	CFE_DOLIST,
	CFE_DOLIST_INS_BASE,
	CFE_DODETAIL,
	CFE_DOINSERT,
	CFE_DOUPDATE,
	CFE_DODELETE,
	CST_DOLIST,
	RNS_DOLIST,
	RNS_DODETAIL,
	RNS_DOINSERT,
	RNS_DOUPDATE,
	RNS_DODELETE,
	RNE_DOLIST,
	RNE_DODETAIL,
	RNE_DOINSERT,
	RNE_DOUPDATE,
	RNE_DODELETE,
	RNU_DOLIST,
	RNU_DODETAIL,
	RNU_DOINSERT,
	RNU_DOUPDATE,
	RNU_DODELETE,
	RNC_DOLIST,
	RNC_DODETAIL,
	RNC_DOINSERT,
	RNC_DOUPDATE,
	RNC_DODELETE,
	CES_DOLIST,
	CES_DOLIST2,
	CES_DODETAIL,
	CES_DOINSERT,
	CES_DOUPDATE,
	CES_DODELETE,
	CES_DOLIST_CONFIG,
	CES_DODETAIL_CONFIG,
	EXI_DOLIST,
	EXI_DODETAIL,
	EXI_DOINSERT,
	EXI_DOUPDATE,
	EXI_DODELETE,
	EXT_DOLIST,
	EXT_DODETAIL,
	EXT_DOINSERT,
	EXT_DOUPDATE,
	EXT_DODELETE,
	RES_DOLIST,
	RES_DODETAIL,
	RES_DOINSERT,
	RES_DOUPDATE,
	RES_DODELETE,
	REE_DOLIST,
	REE_DODETAIL,
	REE_DOINSERT,
	REE_DOUPDATE,
	REE_DODELETE,
	CAR_DOLIST,
	CAR_DODETAIL,
	CAR_DOINSERT,
	CAR_DOUPDATE,
	CAR_DODELETE,
	GTW_DOLIST,
	GTW_DODETAIL,
	GTW_DOINSERT,
	GTW_DOUPDATE,
	GTW_DODELETE,
	GTW_RECUPERA_LISTA_DDL,
	FSC_DOLIST,
	FSC_DOLIST2,
	FSC_DODETAIL,
	FSC_DOINSERT,
	FSC_DOUPDATE,
	FSC_DODELETE,
	
	EC_DOLIST,
	EC_CODFISC,
	EC_DIFF_DOLIST,
	EC_PAGSPON_DOLIST,
	EC_PAGSPON_TIC_DOLIST,
	EC_ACQUTRANS_DOLIST,
	EC_ACQUTRANS_DOLIST_IS,  //20220808 SB
	EC_CONFIG_DOLIST,
	EC_PAG_DOLIST,	//PG160180 GG
	EC_DIFF_DOLIST_ENT,
	
	ECM_DOLIST,
	ECS_DOLIST,
	//KCS-Di Biagio PG140450
	EC_DETBOL,
	//PG150290_001_GG
	EC_ATTICONT_DOLIST,
	
	ECM_DIFF_DOLIST,
	ECS_DIFF_DOLIST,
	ECT_DIFF_DOLIST,
	BOL_DODETAIL,
	CDS_DODETAIL,
	SEC_DODETAIL,
	SEC_DOINSERT,
	SEC_DOUPDATE,
	SEC_DODELETE,
	SEC_DOLIST,
	CAV_DOLIST,
	CAV_DODETAIL,
	CAV_DOINSERT,
	CAV_DOUPDATE,
	CAV_DODELETE,
	CAV_DOPURGE,
	ITE_DOLIST,
	ITE_DOLIST_SESSION,
	ITE_DODETAIL,
	ITE_DOINSERT,
	ITE_DOINSERT_BUFFER,
	ITE_DOUPDATE,
	ITE_DOUPDATE_BUFFER,
	ITE_DODELETE,
	ITE_DODELETE_SESSION,
	ITE_DODELETE_CART,
	ITA_DOLIST,
	ITA_DODETAIL,
	ITA_DOINSERT,
	ITA_DOUPDATE,
	ITA_DODELETE,
	CAS_DOINSERT,
	CAS_DODETAIL, 
	CAS_DOLIST,
	CAS_DODELETE,
	CAS_DOUPDATE,
	TX_SERVIXIO,
	TX_LISTA_TIPO_CARTA,
	TX_LISTA_CANALE,
	TX_LISTA,
	TX_LISTA_ICI,
	TX_LISTA_IV,
	TX_LISTA_FRECCIA,
	TX_UPDATE_TRA,
	TX_PYCFESP_SEL,
	TX_PYCFSSP_SEL,
	TX_LISTA_BY_FESI,
	TX_PYTRASP_SEL_ESITO,
	TX_PYTRASP_SEL_ESITO_PEOPLE,
	TX_PYTRASP_SEL_ESITO_ICI,
	TX_PYTRASP_SEL_ESITO_REND,
	TX_PYTRASP_SEL_BY_CAN_TRAATM,
	TX_PYTRASP_SEL_CHECK_TRAATM,
	TX_PYTRASP_SEL_BANCA,
	TDT_LISTA_PAG_REND,
	TDT_LISTA_PAG_REND_CUP,
	TDT_LISTA,
	TIC_LISTA_PAG_REND,
	TIC_LISTA,
	TFR_LISTA_PAG_REND,
	TDT_LSTNUMDOC,
	TMG_RECUPERA_TRANSAZIONI,
	TMG_RECUPERA_TRANSAZIONI_PDF,
	TMG_RECUPERA_TRANSAZIONI_CSV,
	TMG_RECUPERA_TRANSAZIONI_GROUPED,
	TMG_RECUPERA_TRANSAZIONI_GROUPED_SUCCESS,
	TMG_RECUPERA_TRANSAZIONI_NON_QUADRATE,
	TMG_RIEPILOGO_QUADRATURA,
	TMG_CARTA_DDL,
	TMG_CANALE_DDL,
	TMG_STRUMENTO_DDL,
	TMG_TIPOLOGIA_SERVIZIO_DDL,
	TMG_TIPOLOGIA_SERVIZIO_GET_DDL,
	TMG_GATEWAY_DDL,
	TMG_GATEWAY_GET_DDL,
	TMG_SOCIETA_DDL,
	TMG_SOCIETA_GET_DDL,
	TMG_PROVINCIA_DDL,
	TMG_PROVINCIA_GET_DDL,
	TMG_ENTE_DDL,
	TMG_UTENTE_ENTE_DDL,
	TMG_ENTE_GET_DDL,
	TMG_ENTE_GET_DDL_GENERICI,
	TMG_UTENTE_DDL,
	TMG_UTENTE_GET_DDL,
	TMG_UPDATE_EMAIL_SMS,
	TMG_ELIMINA_TRANSAZIONE,
	TMG_UPDATE_RIF_MOVIMENTO,
	TMG_DETTAGLIO,
	TMG_DETTAGLIO_ICI,
	TMG_DETTAGLIO_FRECCIA,
	TMG_FORZA_ALLINEAMENTO,
	TMG_RECUPERA_TRANSAZIONE,
	TMG_INSERT_MOVIMENTO,
	TMG_UPDATE_MOVIMENTO,
	TMG_CHIUDI_MOVIMENTO,
	TMG_DETTAGLIO_MOVIMENTO,
	TMG_RECUPERA_MOVIMENTI,
	TMG_RECUPERA_MOVIMENTI_GROUPED,
	TMG_RECUPERA_MOVIMENTI_APERTI,
	TMG_ELABORA_MOVIMENTI,
	FLREN_SELBYKEY,
	FLREN_INSRECORD,
	FLREN_SEL_FOR_GRID,
	FLREN_SEL_FOR_GROUP,
	CREN_SELBYCSCUCETS,
	FLREN_UPD_GLOBAL,
	TX_JOINTRATFR,
	TX_JOINTRATDT,
	TX_JOINTRATIC,
	BOL_RECUPERA_LISTA,
	TRA_DOINSERT,
	TDT_DOINSERT,
	DMD_DOINSERT,
	TFR_DOINSERT,
	TIC_DOINSERT,
	FLREN_UPD,
	BOL_RETURN_LIST,
	BOL_DOUPDATE,
	BOL_DOINSERT,
	BOL_DODELETE,
	BOL_DODETAIL2,
	TIT_RECUPERA_LISTA,
	TIT_DOSELECT,
	TIT_DOSELECT2,
	TIT_DOUPDATE,
	TIT_DOINSERT,
	TIT_DODELETE,
	ELG_DODETAIL_NEXT_PELGFILE,
	ELG_DODETAIL_PELGFLUS_BY_NAME,
	ELG_CHECK_PELGFLUS_BY_NAME,
	ELG_DOINSERT, 
	ELG_DOUPDATE,
	ELG_DO_ELG_PELGFLUS,
	ELF_DOINSERT,
	ELF_DOUPDATE,
	EH0_DOINSERT,
	EH1_DOINSERT,
	EH2_DOINSERT,
	EH3_DOINSERT,
	EH4_DOINSERT,
	EH5_DOINSERT,
	EH6_DOINSERT,
	EH7_DOINSERT,
	EH8_DOINSERT,
	EH9_DOINSERT,
	EHX_DOUPDATE,
	EHX_DODELETE,
	EHX_DOPROCESSFLOW,
	EHX_DOPROCESSFLOWROLLBACK,
	EHX_DOUPDATE_ACTIVE_NEW,
	LOG,
	LOG_LST,
	SCA_DOINSERT,
	SCA_DOUPDATE,
	SCA_DOASSIGN,
	SCA_DODELETE_BY_FSCAELAB,
	
	FEC_DOLIST,
	FEC_DODETAIL,
	FEC_DOINSERT,
	FEC_DOUPDATE,
	FEC_DODELETE,
	FEC_DOLIST_ANE,
	FEC_DOLIST_CFENT,
	
	ATM_TX_DOLIST,
	ATM_DOINSERT,
	MNA_INS_LISTA_APPL,
	CEC_DOINSERT,
	CEC_DODETAIL,
	CEC_DOLIST,
	CEC_DODELETE,
	CEC_DOUPDATE,
	CBD_DOINSERT,
	CBD_DODETAIL,
	CBD_DOLIST,
	CBD_DODELETE,
	CBD_DOUPDATE,
	CSN_DOINSERT,
	CSN_DODETAIL,
	CSN_DOLIST,
	CSN_DODELETE,
	CSN_DOUPDATE,
	CTE_DOINSERT,
	CTE_DODETAIL,
	CTE_DODETAIL_AGG,
	CTE_DOLIST,
	CTE_DOLIST_AGG,
	CTE_DODELETE,
	CTE_DODELETE_AGG,
	CTE_DOUPDATE,
	CTS_DOINSERT,
	CTS_DODETAIL,
	CTS_DODETAIL_AGG,
	CTS_DOLIST,
	CTS_DOLIST_AGG,
	CTS_DODELETE,
	CTS_DODELETE_AGG,
	CTS_DOUPDATE,
	CST_DOINSERT,
	CST_DODETAIL,
	CST_DOLISTWEB,
	CST_DODELETE,
	CST_DOUPDATE,
	FLREN_SEL_FOR_CONT,
	FLREN_COD_UTE,	
//	REV_ALGRIV,
	REV_REPORT_CSV,
	REV_ALGRIV2,
	REV_ALGRIV2_NODO,	//PG150180_001 GG
//	REV_ALGCER,
	REV_ALGCER2,
	REV_DOLIST,
	REV_DOSTAT,
	REV_DOUPDATESTAT,
	REV_DOEXEC,
	REV_DOPDF_DC,
	REV_DOCSV,
	REV_DOSEARCH,
	REV_DOUPDFILE,
	REV_DORIVNF,
	REV_DOELANF,
	REV_DOUPDREVCBI,
	REV_UPD_FCBI,
	REV_CHECK_MAIL,
	REV_DODETAIL,
	REV_SEL_BY_CBI,
	ANE_ALL_DODDLIST,
	RED_DOLIST,
	RED_DOLISTSTAT,
	RIV_DOLIST,
	RIV_DOLISTSTAT,
	CBI_DOUPDATE,
	
	// progetto megabottone
	REV_MEGAB,
	//assocBen
	CBP_DODETAIL,
	CBP_DOLIST,
	CBP_DOINSERT,
	CBP_DOUPDATE,
	CBP_DODELETE,
	
	CEB_DODETAIL,
	CEB_TESTVINCOLO,
	CEB_DOLIST,
	CEB_DOLIST_2,
	CEB_DOINSERT,
	CEB_DOUPDATE,
	CEB_DODELETE,
	CEB_DODDLIST,
	APCBEN_CEBDODDLIST,
	ANEBEN_CEBDODDLIST,
	
	CNB_DOLISTREN,
	CNB_DOLISTTRA,
	CNB_DOSEL_PROG,
	CNB_DOUPDATE_GLOBAL,

	BEN_DODETAIL,
	BEN_DOLIST,
	BEN_DOINSERT,
	BEN_DOUPDATE,
	BEN_DODELETE,
	BEN_DODDLIST,
	BEN_DOIMPDDLIST,
	BEN_DOCBPDDLIST,
	APC_BENDODDLIST,
	CFS_DOLIST_INS_BASE2,
	CEN_DODETAIL,
	CEN_DOLIST,
	CEN_DOINSERT,
	CEN_DOUPDATE,
	CEN_DODELETE,
	GTWIMP_DODDLIST,
	
	ENT_DOLIST_MOD21,
	MCG_DOLIST,
	MCG_LST_PERIODI,
	TRA_LST_PRIMO_PER,
	TRA_LST_ERR_BONIFICO,
	MCG_TOT_MOD21,
	MCG_DODETAIL,
	MCG_DOINSERT,
	
	MIP_DOINSERT,
	MIP_DOMIPBK,
	MIP_DOUPDATE,
	MIP_DODETAIL,
	MIP_DODETAIL2,
	MIP_DOLIST,

	//PG150180_001 GG - inizio
	MIN_DOINSERT,
	MIN_DOUPDATE,
	MIN_DODETAIL,
	MIN_DODETAIL2,
	MIN_DOLIST,
	//PG150180_001 GG - fine
	
	MPS_DOINSERT,
	MPS_DOUPDATE,
	MPS_DOCHECK,
	MPS_DOBATCH,
	MPS_DOLIST,
	MPS_DODETAIL,
	MPS_DOCOUNT,
	
	//PG150180_001 GG - inizio
	MPN_DOINSERT,
	MPN_DOUPDATE,
	MPN_DOCHECK,
	MPN_DOBATCH,
	MPN_DOLIST,
	MPN_DODETAIL,
	MPN_DOCOUNT,
	//PG150180_001 GG - fine

	AGE_DOLIST,
	AGI_DOLIST,
	
	AGC_DOINSERT,
	AGC_DODETAIL,
	AGC_DOUPDATE,
	AGC_DOLIST,
	AGC_DOLIST_USERDATE,
	AGC_DOLIST_AUTOMATICO,
	AGC_DOLIST_SCADEVENTO,
	AGC_DOLIST_SCADPREAVVISO,
	AGC_ANALISISCADENZE,
	
	AGU_DOINSERT,
	AGU_DODETAIL,
	AGU_DODETAILFISCALE,
	AGU_DOUPDATE, 
	AGU_DOLIST,
	
	SAN_DODETAIL,
	SAN_DODETAIL_AUT, 
	SAN_DOUPDATE,
	SAN_DOINSERT,
	SAN_DODELETE,
	SAN_DOLIST,
	SAN_DODETAIL_ENT,
	SAN_DOLIST_CSV,
	SAN_DOLIST_CSV_TR,	//PG180170 GG
	SAN_DODETAIL_AU2,	//PG180050_001 GG 
	
	SRG_DODETAIL,
	SRG_DOLIST,
	SRG_DOUPDATE,
	SRG_DOINSERT,
	SRG_DODELETE,
	
	SSG_DOLIST_BELF,
	SSG_DOLIST,
	SSG_DOINSERT,
	SSG_DOUPDATE,
	SSG_DODELETE,
	SSG_DODETAIL,
	SSG_DOLIST_CSV,
	
	SSR_DODETAIL,
	SSR_DOLIST_ALL,
	SSR_DOUPDATE,
	SSR_DOINSERT,
	SSR_DODELETE,
	SSR_DOLIST,
	SSR_DOLIST_CSV,
	
	STF_DODETAIL_WEB,
	STF_DODETAIL,
	STF_DOLIST,
	STF_DOINSERT,
	STF_DOUPDATE,
	STF_DODELETE,
	STF_DOCOUNT_SCT,
	STF_DOLIST_CSV,
	
	SCT_DOINSERT,
	SCT_DOUPDATE,
	SCT_DOLIST,
	SCT_DOLIST_MGR,
	SCT_DODETAIL_WEB,
	SCT_DOLIST_CSV,
	SCT_DOLIST_CSV_TR,
	//PG190300 - inizio
	SCT_DOLIST_SEC,
	SCT_DOCHECK_SEC,
	//PG190300 - inizio
	
	SCD_DOINSERT,
	SCD_DODELETE_SCT,
	
	SDT_DOINSERT,
	SDT_DOUPDATE,
	SDT_DODELETE,
	SDT_DOLIST,
	SDT_OVERLAY,
	SDT_DODETAIL_WEB,

	SDD_DOINSERT,
	SDD_DODELETE_SDT,
	SDD_DOSUM,
	
	IS_ANAG_DOSAVE,
	IS_COMUNICAZIONE_DOSAVE,
	IS_RID_DODETAIL,
	IS_IMPSOGG_DOSAVE,
	
	QUA_RNINCA_QUAINS,
	QUA_RNINCA_TRARIC,
	QUA_RNINCA_QUAEND,
	
	QUA_PAYPAL_QUAINS,
	QUA_PAYPAL_TRARIC,
	QUA_PAYPAL_QUAEND,
	
	QUA_UNICREDIT_QUAINS,
	QUA_UNICREDIT_TRARIC,
	QUA_UNICREDIT_QUAEND,
	
	//inizio LP PG200200
	QUI_RECUPERA_IUV_MOVIMENTI_NODO,
	QUI_LISTIUV,
	QUI_INSERT,
	QUI_UPDATE,
	QUN_DODETAIL,
	//fine LP PG200200
	
	//PG150180_001 GG - inizio
	QUN_NODO_QUNINS,
	QUN_NODO_TRARIC,
	QUN_NODO_QUNEND,
	QUN_RECUPERA_MOVIMENTI_NODO,
	QUN_RECUPERA_MOVIMENTI_GROUPED_NODO,
	QUN_ELABORA_MOVIMENTO_NODO,
	QUN_CHIUDI_MOVIMENTO_NODO,
	QUN_RECUPERA_MOVIMENTI_APERTI_NODO,
	QUN_NODO_UPD,
	TRA_ASSOCIA_FITTIZIO,
	TRA_ASSOCIA_FITTIZIO_MULTIGTW,
	
	PYENTSP_LST_ALL,
	PYECTSP_CHKNAME,
	PYANESP_CHKNAME,
	PYECTSP_INS,
	PYECTSP_DEL,
	PYECTSP_SEL,
	PYECCSP_INS,
	PYECCSP_LST_FLUSSOCBI,
	PYECCSP_LST_NOTIFY,
	PYECCSP_LST_RENDENTE,
	PYECCSP_SEL_ESITOCBI,
	PYECCSP_UPD_ESITOCBI,
	PYECCSP_UPD_RENDENTE,
	PYECCSP_UPD_FLUSSOCBI,
	PYECCSP_UPD_NOTIFY,

	PYECTSP_LST,
	PYECTSP_STAT,
	PYECCSP_SEL,
	
	
	RID_DOINSERT,
	RID_DOUPDATE,
	RID_DODETAIL,
	RID_DODEL,
	RID_DOLIST_BATCH,
	
	POS_DOINSERT,
	
	SELECT_CONFIGURAZIONE,
	VERIFICA_CONFIGURAZIONE,
	SELECT_ALL_CONFIGURAZIONE,
	INSERT_CONFIGURAZIONE,
	DELETE_CONFIGURAZIONE,
	UPDATE_CONFIGURAZIONE,
	SELECT_BY_FILTER_CONFIGURAZIONE,
	
	SELECT_TEMPLATE_DOC, 
	INSERT_TEMPLATE_DOC,
	DELETE_TEMPLATE_DOC,
	UPDATE_TEMPLATE_DOC,
	SELECT_BY_FILTER_TEMPLATE_DOC,
	SELECT_TEMPLATE_DOC_OVERLAY,
	
	SELECT_CONFIGURAZIONE_FLUSSO,
	INSERT_CONFIGURAZIONE_FLUSSO,
	DELETE_CONFIGURAZIONE_FLUSSO,
	UPDATE_CONFIGURAZIONE_FLUSSO,
	SELECT_BY_FILTER_CONFIGURAZIONE_FLUSSO,
	
	SELECT_DETTAGLIO_FLUSSO_OTTICO,
	INSERT_DETTAGLIO_FLUSSO_OTTICO,
	UPDATE_DETTAGLIO_FLUSSO_OTTICO,
	SELECT_ALL_DETTAGLIO_FLUSSO_OTTICO,
	SELECT_ALL_DETTAGLIO_DOC_FLUSSO_OTTICO,
	
	PYEH1SP_LST,
	PYEH1SP_STAT,
	PYELGSP_SEL_DATE,
	
	IG_AGGIORNA_TRANSAZIONI_PENDING,
	
	ONE_DOINSERT,
	ONE_DODETAILTRA,
	TMG_RECUPERA_TRANSAZIONI_GROUPED_ONERI,
	TX_PYRENJOIN_ALL, 
	PYTRA_ANALISI_TENTATIVI,
	PYTSESP_DDL_2,

// batch imposta servizio	
	SRG_ALL_ENTIIS,
	SELECT_PAG_HOST_ENTEIS,
	SCT_UPDATE_DOC,
	SCT_TO_SEND_HOST,
	
	//ENTRATE
	
	EH3_DOLIST,
	EH3_DOLIST_CSV,
	EH8_DOLIST,
	EH8_DODETAIL,
	EH1_DOC_ANA_DOLIST,
	EH1_EMI_S_DODETAIL,
	EH1_DOC_EMI_LST,
	ELG_SEL_DATE,
	EH1_STAT,
	ANE_DDL_UFF,
	ISE_DDL,
	EH6_ISE_DDL,
	EH6_TSE_DDL,
	EH1_DODETAIL,
	EH7_DOLIST,
	EH2_DOLIST,
	EH3_DOC_DOLIST,
	EH7_NOTE_DOLIST,
	EH7_DODETAIL,
	EH1_EMI_DOLIST,
	EH1_EMI_STAT,
	EH1_EMI_DODETAIL,

	//RUOLI
	PYRRUSP_STAT,
	PYRRUSP_LST, 
	PYRRUSP_S_SEL, 
	PYRPASP_LST_RRU, 
	PYRPASP_STAT_RRU, 
	PYRPASP_SEL, 
	PYRARSP_LST,
	PYRARSP_STAT,
	PYRMOSP_LST_DET,
	PYRPASP_LST,
	PYRPASP_STAT,
	PYRANSP_LST,
	PYRANSP_SEL,
	PYRPASP_LST_ANA,
	PYRMOSP_LST,
	PYRMOSP_STAT,
	PYRMOSP_LST_CSV,
	PYRLGSP_SEL_DATE,

	// ruoli integraente
	PYENTSP_LST_RUOLI,
	PYENTSP_IS_REG,
	PYRLGSP_INS_UPD,	
	PYRANSP_INS,
	PYRANSP_UPD,
	PYRRUSP_INS,
	PYRRUSP_UPD,
	PYRPASP_INS,
	PYRPASP_UPD,
	PYRARSP_INS,
	PYRARSP_UPD,
	PYRMOSP_INS,
	PYRMOSP_UPD,
	PYRLFSP_INS,
	PYRRUSP_ELAB,
	PYRRUSP_DEL_TOMB_FLUSSO, 
	
	//batch flussi rend inca
	POF_DODETAIL,
	POF_DOUPDATE,
	POF_DOINSERT, 
	TX_LISTA_REND_POS,
	
	PYKEYSP_BIGINT,
	//Log Anagrafica Figlio Mense
	PYLFMSP_LST,
	//Anagrafica Figlio Mense
	PYAFMSP_LST,
	PYAFMSP_LST_PRE,
	PYAFMSP_LST_TOT,
	PYAFMSP_SEL,
	PYAFMSP_LST_ANNO_SCOL,
	PYAFMSP_LST_PRE_TOT,
	
	//Abilitazione discarico wallet
	PYABDSP_LST,
	PYABDSP_INS,
	PYABDSP_SEL,
	PYABDSP_DEL,
	PYABDSP_UPD,
	
	//Wallet Borsellino 
	PYBRSSP_INS,
	PYBRSSP_SEL,
	PYBRSSP_SEL_ANA,
	PYBRSSP_LST,
	PYBRSSP_LST_RIEP,
	PYBRSSP_LST_DWN_MG,
	PYBRSSP_PGB_ADB_LST,
	PYPGBTB_LST_MG,
	PYBRSSP_SRV_LST,
	PYBRSSP_SRV_LST_ANNO,
	PYBRSSP_SEL_NORID,
	PYSOLSP_ONE_NOP,
	PYBRSSP_REP_VER_CAR,
	PYBRSSP_SRV_RIEP,
	PYBRSSP_SRV_DETT,
	PYBRLSP_LST,
	PYBRSSP_LST_SRV_MG,
	PYBRSSP_UPD,
	PYBRSSP_UPD_ANA,
	PYBRSSP_UPD_FESC,
	PYBRSSP_SOL_LSTSOL,
	PYAFMSP_INS,
	PYSCUSP_INS,	// Scuola
	PYSRVSP_LST,  	// Servizi
	PYTRMSP_LST,   	// Elenco codici Tributo
	PYTRBSP_LST,   	// Elenco codici Tributo tabella tributo
	PYTRBSP_LST_SRV,
	PYBRSSP_LST_SRV,
	PYSOLSP_LST,
	PYSOLSP_INS,
	PYSOLSP_LST_ANNO,
	PYSOLSP_LST_ONE,
	PYPSNSP_LST_DDL,
	PYREPSP_INS,	   //PG130100
	PYASPSP_INS,       //PG130100
	PYFTRSP_INS,       //PG130100   
	PYIFTSP_INS,       //PG130100
	PYICRSP_INS,       //PG130100
	PYCFESP_SEL_TBOLL, //PG130100 recupera tipologia bollettino associato al borsellino
	PYADBSP_LST,       //PG130100 recupera la lista degli adebiti del borsellino
	PYADBSP_LST_DETT,  //PG130100 recupera il dettaglio degli addebiti del borsellino
	PYBRSSP_LST_ANA,
	PYADBSP_POPUP,
	PYUTESP_SEL_SOC,
	PYAFMSP_SEL_SRV,
	PYPGBSP_LST_ANN,
	PYPRMSP_SEL_DAY, 
	PYPRMSP_SEL_ABD,
	PYPGBSP_SEL_ACQ,	//Giulia 5102013---Seleziona la somma degli importi in acquisizione
	PYPGBSP_SEL_APPL,	//PG180040 GG 18062018
	PYBRSSP_NEWIDBRL,
	// Congigurazione Solleciti
	PYCSLSP_INS,	
	PYCSLSP_DEL,
	PYCSLSP_UPD,
	PYCSLSP_LST,
	PYCSLSP_SEL,
	
	// Congigurazione Evoluzione Intimazioni
	PYSLISP_INS,	
	PYSLISP_DEL,
	PYSLISP_UPD,
	PYSLISP_LST,
	PYSLISP_SEL,

	// Congigurazione Pagamento per Servizio
	PYPPSSP_INS,	
	PYPPSSP_DEL,
	PYPPSSP_UPD,
	PYPPSSP_LST,
	PYPPSSP_SEL,

	// Congigurazione Attribuzione Pagamento sul Servizio
	PYPASSP_INS,	
	PYPASSP_DEL,
	PYPASSP_UPD,
	PYPASSP_LST,
	PYPASSP_SEL,

	// Pagamento Borsellino
	PYPGBSP_LST,	
	PYPGBSP_LST_DETT,
	
	// Congigurazione Raccordo Pagonet
	PYRCPSP_INS,	
	PYRCPSP_DEL,
	PYRCPSP_UPD,
	PYRCPSP_LST,
	PYRCPSP_SEL,
	 
	// Notifica Pagamento per WS Pagamenti Totem, Sisal e Lottomatica	//PG130130 GG
	PYATMSP_UPD,
	PYTDTSP_UPD, 
	
	//PDF CERTIFICAZIONE
	PYAFMSP_LST_SRV,
	PYSRVSP_SEL, 
	PYPRMSP_INS,
	PYPRMSP_INS_DIS,
	PYPGBSP_AGG_PAGAM,
	PYBRSSP_ALL_DISP,
	PYSISSP_LST,
	SPEPPAGN,
	PYPGBSP_PAG_WEB, 
	PYPGBSP_LST_TRI, 
	PYBRSSP_LST_SMSEMAIL,
	PYSOLSP_UPD_LSTW,
	PYSOLSP_DEL_SOL,
	PYSOLSP_UPD_ESITOSMS,
	
	//SP Pagamenti Borsellino HOST
	PGBHOST,
	PYPGHSP_INS,
	PYPGHSP_LST,
	PYPGHSP_LST_DETT,
	PYPGHSP_DEL,
	PYSISSP_GENERA,
	PYBRSSP_SEL_ID,

	//SP SEPA
	SDDAUSP_SEL_BRS,
	PYSNTSP_FOR_SORINET,
	PYSNTSP_AGGIORNA,
	SDDDESP_INS_BRS,
	
	//SP Gestione Avvisi
	PYMSGSP_LST,
	PYMSGSP_SEL,
	PYMSGSP_UPD,
	
	//Estratto Conto Anagrafica Bollettino
	PYECASP_SEL,
	PYECASP_LST_ANA,
	PYECASP_UPD_PACC,
	PYECABRS_RPT,
	PYECBRLOG_RPT,
	PYECASP_UPD,
	PYECASP_INS,	//PG170200 GG
	PYECASP_UPD_PIN, //PG170180 CT
	
	//Sosta Atac
	PYSATSP_SEL

	//PG150180_001 GG - inizio
	//NodoSpc
	,PYPSPSP_LST_DDL //elenco PSP aderenti al nodo nazionale spc
	,PYPSPSP_INS //inserimento PSP del nodo nazionale spc
	,PYPSPSP_DEL //svuotamento tabella PSP
	//,PYIUVSP_INS //inserimento IUV
	//,PYIUVSP_UPD_IUV //update IUV
	//,PYIUVSP_UPD_RT //update RT
	,PYPSCSP_LST //elenco PSC = canali di pagamento di un PSP
	,PYPSCSP_DEL //svuotamento tabella PSC
	,PYPSCSP_INS //inserimento canale di pagamento di un PSP
	,PYRPTSP_INS //inserimento RPT
	,PYRPTSP_UPD //update RPT
	,PYRPTSP_SEL //select RPT
	//PG150180_001 GG - fine
	//PG150140_001 GG - inizio
	,PYSANSP_SEL_CFIS
	,SPEPIT01
	,SPEPIT02
	//PG150140_001 GG - fine
	,PYAFMSP_SEL_CFIS	//PG150310_001 GG
	,PYAFMSP_UPD_FSOS	//PG150330_001 GG
	,CNCNFSP_LST //configurazione blackbox list
	,CNCNFSP_UPD
	,CNCNFSP_SEL
	,CNCNFSP_INS
	,CNCNFSP_DEL
	,CNCNFSP_PST_LST // recupera la lista degli enti configurati per l'integrazione con poste
	//PG180080 inizio
	,PYMDTSP_LST//configurazione modello 3 list
	,PYMDTSP_UPD
	,PYMDTSP_SEL
	,PYMDTSP_INS
	,PYMDTSP_DEL
	//PG180080 fine
	//PG170070_001 GG - inizio
	,PYEH1SP_DE2
	,PYEH1SP_SE2
	,PYEH1SP_SEL3
	,PYEH2SP_SE2
	,PYEH3SP_SE2
	,PYEH6SP_SE2
	,PYEH7SP_SE2
	,PYEH8SP_SE2
	,PYEH6SP_UP2
	,PYEH8SP_UP2
	,EHX_DOACROLLBACK
	,PYEH3SP_SEL_PPAG
	,PYPRGSP_NXT
	,PYEHXSP_CHK_IUV
	,PYELGSP_SEL_FELGESTA
	,PYEH1SP_SEL_FELGESTA
	,PYELGSP_SE2
	,PYEH0SP_SE2
	,PYEH9SP_SE2
	,PYEH0SP_UP2
	,PYEH9SP_UP2
	,PYEHXSP_PAG
	,PYEHXSP_DIS
	//PG170070_001 GG - fine
	,PYTRASP_MONITORAGGIO_TRANSAZIONI
	,ALL_ANA_CONTATTO	//PG170200 GG
	,EH1_FLAGSTAMPA
	, NEX_DODETAIL //PG170150 CT	
	, NEX_DOUPDATE //PG170150 CT
	, NEX_DOINSERT //PG170150 CT
	//, NEX_DOLIST //PG170150 CT
	,PYTDTSP_UPD_IUR
	,PYTFRSP_UPD_IUR
	,PYTICSP_UPD_IUR
	,PYKEYSP_BY_YEAR //PG180050_001 GG
	//PG180040 - MERCATO - PG
	,PYTPBSP_LST
	,PYTPBSP_INS
	,PYTPBSP_UPD
	,PYTPBSP_DEL
	,PYTPBSP_TOT
	,PYTPBSP_SEL
	,PYMRCSP_LST
	,PYMRCSP_INS
	,PYMRCSP_UPD
	,PYMRCSP_DEL
	,PYMRCSP_SEL
	,PYMRCSP_TOT
	,PYMRCSP_APD
	,PYPEGSP_LST
	,PYPEGSP_INS
	,PYPEGSP_UPD
	,PYPEGSP_DEL
	,PYPEGSP_TOT
	,PYPEGSP_SEL
	,PYAUTSP_LST
	,PYAUTSP_INS
	,PYAUTSP_UPD
	,PYAUTSP_DEL
	,PYAUTSP_SEL
	,PYAUTSP_TOT
	,PYAUTSP_NOM
	,PYPZLSP_LST
	,PYPZLSP_INS
	,PYPZLSP_UPD
	,PYPZLSP_DEL
	,PYPZLSP_SEL
	,PYPZLSP_TOT
	,PYPZLSP_APM
	,PYPZLSP_SEK
	,PYPZLSP_UPK
	,PYTAMSP_LST
	,PYTAMSP_INS
	,PYTAMSP_UPD
	,PYTAMSP_DEL
	,PYTAMSP_SEL
	,PYTAMSP_TOT
	,PYTAMSP_APA
	,PYTAMSP_SLK
	,PYTAMSP_UPK
	,PYTAMSP_APL
	,PYTAMSP_MON
	,PYTAMSP_MNL
	,PYTAMSP_MTT
	,PYCOMSP_LST
	,PYCOMSP_INS
	,PYCOMSP_UPD
	,PYCOMSP_DEL
	,PYCOMSP_SEL
	,PYCOMSP_TOT
	,PYPRNSP_SEL
	,PYPRNSP_INS
	,PYPRNSP_UPD
	,PYPRNSP_DEL
	,PYPRNSP_SLT
	,PYPRNSP_DLK
	//RR
	,PYACMSP_SEL_CF
	,PYACMSP_INS
	,PYBRSSP_AGG_OND
	,PYPZLSP_LST_PRN
	,PYPRNSP_SLK
	,PYADBSP_INS_OND
	,PYMRCSP_LST_DATE
	,PYACMSP_UPD
	//inizio LP 20180629
	,ENT_DODETAIL_CODFIS
	//fine LP 20180629
	//inizio LP 20180711
	,FLREN_UPD_GLOBAL_EVOL
	,FLREN_UPD_GLOBAL_LIST
	,CNB_DOUPDATE_GLOBAL_EVOL
	,CNB_DOUPDATE_GLOBAL_LIST
	//fine LP 20180711
	//inizio LP PG1800XX_016
	, SFI_DOLIST
	, SFI_DOLIST_KEY
	, SFI_DODETAIL
	, SFI_DODETAIL_WEB
	, SFI_DOINSERT
	, SFI_DOUPDATE
	, SFI_DODELETE
	, SCT_DOLIST_CSV_SS
	//fine LP PG1800XX_016
	//PG180180 GG - inizio
	, PYCBNSP_SEL
	, PYCBNSP_INS
	//PG180180 GG - fine
	,EYUTESP_INS
	,EYUTESP_SEL
	,PYGAGSP_LST  //RE180181 SB
	,PYGAGSP_LST_DDL  //RE180181 SB
	,PYGAGSP_DEL  //RE180181 SB
	,PYGAGSP_INS  //RE180181 SB
	,PYGAGSP_UPD  //RE180181 SB
	,PYGAGSP_SEL  //RE180181 SB
	,SPEPSTE1     //PG180200_001 SB
	,DO_DATI_BOLLETTINO  //PG190300 SB
	,DO_BOLLETTINO_CUMULATIVO  //PG190300 SB
	,PYSANSP_LST_ALL    //PG190330 SB
	,SAN_DDL_ALLOGGI   //PG190330 SB
	,DO_RIEPILOGO   //PG190330 SB
	,PYBRSSP_LST_CSV  //PG190400 SB
	//inizio LP PG200060
	//PG14001X_001 - inizio
	//CUP
	,PYCUPSP_INS
	,PYCUPSP_UPD
	,PYCUPSP_SEL
	,PYCUPSP_LST
	,MIC_DOINSERT
	,MIC_DOUPDATE
	,MIC_DODETAIL
	,MIC_DOLIST
	,MCS_DOINSERT
	,MCS_DOUPDATE
	,MCS_DOCHECK 
	,MCS_DOLIST 
	,MCS_DOBATCH 
	,MCS_DODETAIL 
	,MCS_DOCOUNT
	,MCP_DODETAIL2
	//PG14001X_001 - fine
	,PYCFTSP_LST
	,PYCFTSP_SEL
	,PYCFTSP_INS
	,PYCFTSP_UPD
	,PYCFTSP_DEL
	,PYPABSP_SEL
	,PYPABSP_INS
	,PYPABSP_UPD
	,PYPABSP_DEL
	,PYPABSP_LST
	//PG200120 - inizio
	,CNDOCSP_LST 
	,CNDOCSP_DEL
	,CNDOCSP_UPD
	,CNDOCSP_SEL
	,CNDOCSP_LSTENT
	,CNDOCSP_LST_EC
	,CNDOCSP_DET_EC
	,CNDOCSP_MOV_EC
	,CNDOCSP_UPD_PAG
	//PG200120 - fine
	,ENT_DODETAIL_CODFIS_KENTE
	,CNKEYSP //PG200180
	,CNDOCSP_INS  //PG200180
	,PYRPTSP_SEL_KANE_BY_IUV
	,DESCRSERVDESCRENTE	//PG200120
	,CNDOLSP_LST //PG200120
	,CNDOLSP_DEL //PG200120
	,CNDOLSP_INS //PG200120
	//inizio LP PG200360
	,PYTASSP_INS
	,PYTASSP_DEL
	,PYTASSP_GET
	,PYTASSP_LST
	,PYTASSP_SEL
	,PYTASSP_UPD
	,PYTASSP_CHK
	//fine LP PG200360
	,CNKEYSP_GG
	, PYSTSSP_UPD //PG200400
	, PYTRASP_MONITORAGGIO_TRANSAZIONI_V2 //PG210060
	//inizio LP PG210040
	,PYGRPSP_INS
	,PYGRPSP_DEL
	,PYGRPSP_GET
	,PYGRPSP_LST
	,PYGRPSP_SEL
	,PYGRPSP_UPD
	,PYGRPSP_CHK
	//fine LP PG210040
	, CNPSTSP_INS
	, CNDOCSP_PST_INS
	, CNDOCSP_PST_LST
	, CNDOCSP_PST_SEL
	, CNDOCSP_PST_UPD
	, PYRPTSP_PST_SEL
	, PYANESP_SEL_DOMINIO //LP PG210130 Step02
	, CNPSTSP_MAN_LST
	, CNDOCSP_PST_MAN_LST
	, CNPSTSP_SEL
	//fine PG210100
	, PYEHXSP_FIO	//PG210210
	//inizio LP PG21X007
	, PGSP_EXIST_TABLE
	, PGSP_BACKUP_TABLE
	, PGREQSP_INS
	, PGREQSP_UPD
	, PGREQSP_UPD_EXT
	, PGREQSP_LST
	, PGREQSP_SEL
	//fine LP PG21X007
	, PGWINSP_INS
	, PGWINSP_LST
	, PGWINSP_SEL
	, PGPAPSP_INS
	, PGPAPSP_LST
	, PGPAPSP_SEL
	, LOG_INVALIDATE
	, LOG_DETAIL
	// PG210160
	, PYFORSP_LST
	, PYFORSP_INS
	, PYFORSP_SEL
	, PYIICSP_LST
	, PYIICSP_INS
	, PYIICSP_UPD
	, PYIICSP_SEL
	, PYIICSP_SEL2
	, PYIICSP_DEL
	, PYMESSP_INS
	, PYMESSP_UPD_STA
	, PYMESSP_SEL_STA
	, PYMESSP_SEL
	, PYMESSP_UPD
	, PYMESSP_DEL
	, PYMESSP_LST
	, PYIICSP_ABIL_SEL
	, PYMESSP_SEL2
	, PYEH2SP_IOIT
	, PYIICSP_SEL3
	// fine PG210160
	// PG210110
	, CNDOCSP_IOIT
	// fine PG210110
	// INIZIO PG210200
	, PYCFTSP_SEL_BATCH
	, PYRPTSP_SEL_BATCH
	, PYQUNSP_SEL_BATCH
	, PYQUNSP_UPD_BATCH
	, PYRPTSP_UPD_BATCH
	// FINE PG210200
	// YLM PG22XX06 INI
	, PYFORSP_LST_APPIO
	, PYFORSP_SEL_APPIO
	, PYIICSP_LST_APPIO
	, PYIICSP_SEL_APPIO
	, PYMESSP_LST_APPIO
	, PYIICSP_SEL_APPIO2
	, PYIICSP_SEL_APPIO3
	, PYCFESP_LST_APPIO
	// YLM PG22XX06 FINE
	// YLM PG22XX07 INI
	, PYNEXSP_LST_MG
	, PYNEXSP_SEL_MG
	, PYNEXSP_UPD_MG
	// YLM PG22XX07 FINE
	//PG22XX09_SB2 - inizio
	, PYSELSP_INS
	, PYSELSP_UPD
	, PYSELSP_SEL
	, SDDAUSP_INS
	, SDDASSP_INS
	, SDDAUSP_SEL
	//PG22XX09_SB2 - fine
	// YLM PG22XX08 INI
	, PGPAPSP_OPE_DDL
	// YLM PG22XX08 FINE
	//PGNTCORE-1 SB INIZIO
	, PYTDTSP_LST_ENT
	//PGNTCORE-1 SB FINE
	, EHD_DOINSERT
	;
	
    private static ResourceBundle rb;

    public String routine() {
        synchronized(Routines.class) {
            if(rb==null)
                rb = ResourceBundle.getBundle(Routines.class.getName());
            return rb.getString(name());
        }
    }
}