package com.seda.payer.core.dao;

import java.util.ResourceBundle;

public enum StoredProcConf {
	CARTA_ALL_TEXT,
	CARTA_ALL_VALUE,
	CARTA_PREFIX,
	SERVIZIO_ALL_TEXT,
	SERVIZIO_ALL_VALUE,
	SERVIZIO_PREFIX,
	CANALE_ALL_TEXT,
	CANALE_ALL_VALUE,
	CANALE_PREFIX,
	SOCIETA_ALL_TEXT,
	SOCIETA_ALL_VALUE,
	SOCIETA_PREFIX,
	AMBITOUTENTE_ALL_TEXT,
	AMBITOUTENTE_ALL_VALUE,
	AMBITOUTENTE_PREFIX,
	ENTECONSORZIO_ALL_TEXT,
	ENTECONSORZIO_ALL_VALUE,
	ENTECONSORZIO_PREFIX,
	ENTECONSORZIATO_ALL_TEXT,
	ENTECONSORZIATO_ALL_VALUE,
	ENTECONSORZIATO_PREFIX,
	TRA_USER_EMAIL,
	TRA_USER_SMS,
	TRA_USER_INDI,
	TRA_USER_CAP,
	TRA_USER_CITTA,
	TRA_USER_PROV,
	TRA_SOSPESA,
	STATORENDICONTAZIONE_ALL_VALUE,
	STATORICONCILIAZIONE_ALL_VALUE,
	TIPOLOGIA_SERVIZIO_ALL_TEXT,
	TIPOLOGIA_SERVIZIO_ALL_VALUE,
	TIPOLOGIA_SERVIZIO_PREFIX,
	STRUMENTO_ALL_TEXT,
	STRUMENTO_ALL_VALUE,
	STRUMENTO_PREFIX,
	UTENTE_ALL_TEXT,
	UTENTE_ALL_VALUE,
	UTENTE_PREFIX,
	PROVINCIA_ALL_VALUE,
	PROVINCIA_ALL_TEXT,
	PROVINCIA_PREFIX;

	private static ResourceBundle rb;

	    public String getParam() {
	        synchronized(StoredProcConf.class) {
	            if(rb==null)
	                rb = ResourceBundle.getBundle(StoredProcConf.class.getName());
	            return rb.getString(name());
	        }
	    }
	}